config/routes.rb
HackstarAcademy::Application.routes.draw do
  get "pages/home"

  get "pages/home_test"
  
  get "pages/dates"
  
  get "pages/testimonials"

  get "pages/about"
  
  get "pages/faq"
  
  root :to => "pages#home"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def home_test
  end
  
  def dates
  end

  def testimonials
  end

  def about
  end
  
  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Hackstar Academy</title>
		<link href='http://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Voces' rel='stylesheet' type='text/css'>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
		<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-31182348-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
	</head>
	<body>	
		
		
		<%= render :partial => "shared/header" %>	
		<div class="container container-body">
				<br />
				<br />				
			<% if notice %>
				<br />
				<p class="alert alert-success">
					<a class="close" data-dismiss="alert">&times;</a>
						<%= notice %>
				</p>
			<% end %>
	
			<% if alert %>
			<br />
				<p class="alert alert-error">
					<a class="close" data-dismiss="alert">&times;</a>
						<%= alert %>
				</p>
			<% end %>
		
			
			<%= yield %>

		</div>
		<%= render :partial => "shared/footer" %>		
		
		
		<!-- begin olark code --><script type='text/javascript'>/*{literal}<![CDATA[*/
		window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){f[z]=function(){(a.s=a.s||[]).push(arguments)};var a=f[z]._={},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={0:+new Date};a.P=function(u){a.p[u]=new Date-a.p[0]};function s(){a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{b.contentWindow[g].open()}catch(w){c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{var t=b.contentWindow[g];t.write(p());t.close()}catch(x){b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
		/* custom configuration goes here (www.olark.com/documentation) */
		olark.identify('2809-307-10-6116');/*]]>{/literal}*/</script>
		<!-- end olark code -->
		
	</body>
</html>

app/views/pages/Home-test.html.erb
<body class="home">
<div style="margin-bottom:35px; margin-top:-18px; text-align:center">	
	<h1><span style="font-size:44px;">Hackstar Academy</span></h1>
</div>
<div id="content-home">
	<h1>Summer Programming Fellowship for Women</h1>
	<p>
	</p>	
	<ul>
		<li>
			<i class="icon-ok"></i>
			<span class="content-home-check">Become a software developer in 10 Weeks</span>
		</li>
		<li>
			<i class="icon-ok"></i>
			<span class="content-home-check">Located in San Francisco, CA</span>
		</li>  
		<li>
			<i class="icon-ok"></i>
			<span class="content-home-check">Job and Internship Opportunities</span>
		</li>	
	</ul>
	<a class="btn btn-success btn-home" href="http://bit.ly/Ic4s8Y" target="_blank">Apply Today
		<br />
		<span id="small-btn-font">(space is limited)</span>
	</a>	
</div>     

<div class="row">	
  <div class="span4">
		<img id="column-1" src="../assets/Women-who-code.png" width="373" height="74" alt="Summer Fellowship">
			<h2>The Programming Fellowship</h2>
		<p>
		10-week intensive program to train you to become a software developer.  Located in the heart of San Francisco: June 18 - August 24. Application Deadline: 5/30</p> 
  </div>
	<div class="span4" style="margin-top:18px;">
		<div id="column-2">
			<h2>Our Mission</h2>
		</div>
		<p>Our mission is to teach people software development in order to help them pursue their passions.</p>
  </div>
  <div class="span4">
		<img id="column-3" src="../assets/content.png" width="373" height="74" alt="Mission" >
    <h2>Python</h2>
	 	<p>We believe python is the best learning language and a lot of awesome companies use it.  We also teach you the skills necessary to be a great developer in any language, with any framework.</p>
  </div>
</div>
<hr>
<div class="row">
<div class="span12">

                  <div class="item active">
										<div class="row space2">
												<div class="span2">
                          <div class="thumbnail home-testimonial">
                            <%= image_tag "ashley.png"%>
                          </div>
												</div>
												<div class="span2">
													<h3>Ashley</h3>
													<h6>Software Dev Consultant</h6>
													<p>"I would highly recommend Christian as a teacher to any woman interested in learning software development... "<br /><a href="/pages/testimonials">Read More</a></p>
												</div>
												<div class="span2">
                          <div class="thumbnail">
                            <%= image_tag "shail.png"%>
                          </div>
												</div>
												<div class="span2">
													<h3>Shail</h3>
													<h6>Support Engineer @ Ooyala</h6>
													<p>"Hands down, Christian is the best teacher I've ever had... "<br /><a href="/pages/testimonials">Read More</a></p>
												</div>
												<div class="span2">
                          <div class="thumbnail">
                            <%= image_tag "janiney.png"%>
                          </div>
												</div>
												<div class="span2">
													<h3>Janine</h3>
													<h6>VP Biz Dev @ TokBox</h6>
													<p>"Christian is not only all patience and no condescension, but is gifted at explaining clearly how things work, all the way down to brass tacks... "<br /><a href="/pages/testimonials">Read More</a></p>
												</div>
										</div>
										<div class="row space2">
												<div class="span2">
                          <div class="thumbnail">
                            <%= image_tag "doug.png"%>
                          </div>
												</div>
												<div class="span2">
													<h3>Doug</h3>
													<h6>Junior Developer @ DailyKos</h6>
													<p>"I would recommend Christian to anyone, beginner to
													expert, looking for a more nuanced and thorough understanding of the
													art of coding...."<br /><a href="/pages/testimonials">Read More</a></p>
												</div>
												<div class="span2">
                          <div class="thumbnail">
                            <%= image_tag "adam.png"%>
                          </div>
												</div>
												<div class="span2">
													<h3>Adam</h3>
													<h6>Lead Developer @ Bungalow</h6>
													<p>"Christian is a wonderful instructor who has a gift for turning complex ideas into something understandable..."<br /><a href="/pages/testimonials">Read More</a></p>
												</div>
												<div class="span2">
                          <div class="thumbnail">
                            <%= image_tag "craig.png"%>
                          </div>
												</div>
												<div class="span2">
													<h3>Craig</h3>
													<h6>Engineer @ Zendesk</h6>
													<p>"I highly recommend any program with which he is involved..."<a href="/pages/testimonials">Read More</a></p>
												</div>
										</div>
									</div>
								</div>
							</div>
						</div>
<div class="row">					
	<div id="home-support" class="span13">
		<h3>Supported by</h3>
		<br />	
	<p class="span3">
	<a href="http://www.thedailymuse.com" target="_blank"><img src="../assets/DailyMuse_logo.png" width="200" height="74" alt="The Daily Muse"></a>
	</p>
	<p class="span3">
	<a href="http://www.women2.com" target="_blank"><img src="../assets/women2_logo.jpg" width="200" height="74" alt="Women 2.0"></a>
	</p>
	<p class="span3">
	<a href="http://www.kicklabs.com" target="_blank"><img src="../assets/KLpja.jpg" width="200" height="74" alt="Kicklabs"></a>
	</p>

	<p class="span3">
	<a href="http://www.tokbox.com" target="_blank"><img src="../assets/tokbox.jpg" width="200" height="74" alt="new relic"></a>
	</p>
	
</div>
</div>	
</body>

app/views/pages/about.html.erb
<center>
	<div style="margin-bottom:20px; margin-top:-18px">	
	<h1><span style="font-size:44px;">Hackstar Academy</span></h1>
	</div>

</center>

<div class="span2">
<p></p>
</div>
<div class="span7">
<h2>Our Programming Fellowship</h1>
<p>It's a 10 week training program designed to help women become awesome programmers. We teach the fundamentals of modern web development, then introduce you to Silicon Valley companies looking to expand their engineering teams.</p>
	
<h2>About Us</h2>
<p>We are just a couple of nerds who are passionate about teaching the world how to code.</p>
<ul class="thumbnails">
       				<li class="span7">
          <div class="thumbnail">
					<%= image_tag "christian.png", :style => "float:left; margin:15px;"  %>
            <div class="caption">
							<h3 class="role">Instructor</h3>
              <h3>Christian Fernandez</h3>
							<br />
              <p>Christian grew up on the tropical island of American Samoa, learning to hunt eels in the coral reefs. He applied those skills later to write assembly code to blit bitmaps in mode 13h (doing graphics with assembly is a lot like eel-wrangling). These days, he's hung up his eel gloves in favor of building network applications and teaching programming. He's been a senior software developer at <a href="http://www.telecomsys.com/" target="_blank">Kivera</a> (acquired by TCS), <a href="http://www.ask.com" target="_blank">Ask</a>, and <a href="https://fuzebox.com/" target="_blank">Fuzebox</a>.<br /><br /> He's also a founding member and resident python instructor at <a href="http://acemonstertoys.org/" target="_blank">Ace Monster Toys</a>, an educational hackerspace in Oakland, and was an instructor for the inaugural class of <a href="http://www.devbootcamp.com" target="_blank">DevBootcamp</a>.  Christian holds a B.S. in Computer Science and Electrical Engineering from the University of California, Berkeley.</p>  
            </div>
          </div>
        </li>
				 <li class="span7">
	          <div class="thumbnail">
							<%= image_tag "david.png", :style => "float:left; margin:15px;"  %>
	            <div class="caption">
								<h3 class="role">TA</h3>
	              <h3>David J. Phillips</h3>								<br />
	              <p>David enjoys programming, making music, and living in San Francisco.  He wrote his first program in Java when he was 16.  He also has a passion for good design.  Since starting his career at <a href="http://www.deloitte.com" target="_blank">Deloitte</a>, he has been lucky enough to start companies (<a href="http://www.ban.jo" target="_blank">Banjo</a>) and build products (<a href="http://www.getcustard.com" target="_blank">Custard</a>, <a href="http://www.bibbil.com" target="_blank">Bibbil</a>) that reach over a million users across the world.<br /><br />  After catching the startup bug, David started to learn how to build web applications using modern technologies. He holds a B.A. in Business Economics from the University of California, Santa Barbara.</p>  
	            </div>
	          </div>
	        </li>
				
				<li class="span7">
					<h2>Advisors</h2>
          <div class="thumbnail">
					<%= image_tag "janine.png", :style => "float:left; margin:15px;"  %>
            <div class="caption">
              <h3>Janine Yoong, VP of Business Development</h3>
							<h6>TokBox</h6>
							<br />
              <p>Janine gets front row seats to watch amazing apps come to life as she works with TokBox partners. Before joining Tokbox in April 2010, Janine worked at Google driving advertising partnerships in the local space. During her three years at Google, she worked with Yellow Pages companies, newspaper publishers, auto ad agencies and geo-local startups to put together advertising solutions for small businesses. Prior to Google, Janine worked at Yahoo! in Operations Finance supporting the HotJobs business unit. In addition to planning and strategic review, she acted as lead analyst for the first phase of the Yahoo Newspaper Consortium, Yahoo's partnerships with over 200 newspapers on its local ad management platform. Janine was an Investment Banking Analyst at Lehman Brothers in the Financial Institutions Group from 2003 - 2005.<br /><br /> Janine holds a B.A. in International Affairs and Public Policy from Princeton University.</p>  
            </div>
          </div>
        </li>
				<li class="span7">
          <div class="thumbnail">
					<%= image_tag "alex.png", :style => "float:left; margin:15px;"  %>
            <div class="caption">
              <h3>Alex Cavoulacos, Founder and COO</h3>
							<h6>The Daily Muse</h6>
							<br />
              <p>Alex makes things work at The Daily Muse. From operations to product, she’s our #1 list maker. Prior to founding The Daily Muse, Alex was a management consultant, solving critical strategic and operational questions for top firms worldwide. She graduated from Yale University, where she was the Executive Director of Global21 – a network of international affairs magazines at premier universities around the world. It was there that she first gained experience in publishing, managing a team of 300 on 6 continents, and reaching over a quarter of a million readers with print magazines. Follow her on Twitter @acavoulacos.</p>  
            </div>
          </div>
        </li>
				  
      </ul>

</div>

app/views/pages/dates.html.erb
<center>
	<div style="margin-bottom:20px; margin-top:-18px">	
	<h1><span style="font-size:44px;">Hackstar Academy</span></h1>
	</div>

</center>

<div class="span2">
<p></p>
</div>
<div class="span7">
	<div >
		<h2>Dates</h2>
		<p>Our 10-week training program runs from 10:00am to 6:00pm, Monday through Friday. We are located at 2017 Mission St. in San Francisco, CA.</p>
		
		<h3>Summer 2012<small> (FULL, thanks everyone!)</small></h3>
		<table class="dates">
		    <tbody>
		    <tr>
		      <td>May</td><td>30:</td><td>Application Deadline</td>
		    </tr>
		    <tr>
		      <td>June</td><td>18:</td><td>Class begins</td>
		    </tr>
		    <tr>
		      <td>August</td><td>24:</td><td>Class ends</td>
		    </tr>
		  </tbody></table>
			<br />
			<h3>Fall 2012<small> (Now Accepting Applications) </small></h3>
			<table class="dates">
			    <tbody>
			    <tr>
			      <td>July</td><td>15:</td><td>Early Application Deadline</td>
			    </tr>
			    <tr>
			      <td>July</td><td>30:</td><td>Early Admissions Decision</td>
			    </tr>
			    <tr>
				    <td>August</td><td>15:</td><td>General Application Deadline</td>
				  </tr>
				  <tr>
				    <td>August</td><td>30:</td><td>General Admissions Decision</td>
				  </tr>
					<tr>
			      <td>October</td><td>1:</td><td>Class begins</td>
			    </tr>
					<tr>
			      <td>December</td><td>7:</td><td>Class ends</td>
			    </tr>
				  </tbody></table>
			<br />
			<h3>Spring 2013<small></small></h3>
			<table class="dates">
			    <tbody>
			    <tr>
			      <td>October</td><td>1:</td><td>Early Application Deadline</td>
			    </tr>
			    <tr>
			      <td>October</td><td>20:</td><td>Early Admissions Decision</td>
			    </tr>
			    <tr>
			      <td>November</td><td>15:</td><td>General Application Deadline</td>
			    </tr>
			    <tr>
			      <td>December</td><td>31:</td><td>General Admissions Decision</td>
			    </tr>			
			    <tr>
			      <td>February</td><td>4:</td><td>Class begins</td>
			    </tr>
					<tr>
			      <td>April</td><td>12:</td><td>Class ends</td>
			    </tr>
			  </tbody></table>
</div>
</div>	

app/views/pages/faq.html.erb
<center>
	<div style="margin-bottom:20px; margin-top:-18px">	
	<h1><span style="font-size:44px;">Hackstar Academy</span></h1>
	</div>

</center>

<div class="span2">
<p></p>
</div>
<div class="span7">
<h2>Our Programming Fellowship</h1>
<p>It's a 10 week training program designed to help women become awesome programmers. We teach the fundamentals of modern web development, then introduce you to Silicon Valley companies looking to expand their engineering teams.</p>

<h2>What will you learn?</h2>
<p>Here is what you will learn. Some words you may not understand when you start, but will when you finish:</p>
		<li>Python and its associated web frameworks</li>
		<li>Pair programming</li>
		<li>Git and source control</li>
		<li>Interview skills</li>
	  <li>SQL and ORMs, and NoSQL</li>
	  <li>HTML, CSS, JS, Ajax, and WebSockets</li>
	  <li>Deploying into EC2 and GAE</li>
	  <li>Terminal shells, grep, netcat, and other *nix command-line fu</li>
	  <li>Message queues, batch processing, distributed processing</li>
	  <li>Why some nerds really love lisp, vim, and emacs</li>
	</p>
	
<h2>When and Where?</h2>
<p>The program is full-time, Monday through Friday, from 10AM to 6PM, in our San Francisco office: 2017 Mission St. We supply the computers, you supply the enthusiasm.</p>
<h2>What’s it like?</h2>
<p>The Hackstar Fellowship is a life changing experience. We create an optimal learning environment with everything you need. The first half of the program includes an accelerated in depth teaching of the Python language, then covers the elements of a modern web application stack with guided projects. For the remainder of the program, students work on projects they’re passionate about. Meanwhile, we’ll bring in guests from great companies and have talks and breakout sessions exposing students to as many sub-disciplines as we can manage.</p>

<p>We believe in pair programming as a powerful teaching tool. Having another person sitting next to you watching you code can be harrowing, but nothing keeps you focused like a second set of eyes. Pair programming encourages knowledge sharing, rapid brainstorming, and keeps you from checking Facebook too much. Students will pair as much as possible during the program.</p>

<p>We won’t lecture too much. We believe fully immersed engagement is the best way to learn. We provide the curriculum and environment to produce optimal learning. This means maximizing hands-on time in front of computers and providing smart people who can answer all of your questions.</p>

<h2>Who is this for?</h2>
<p>Our ideal candidate has a strong, inspired desire to learn software development. You may have some technical experience but want an immersive environment to become a good developer. Maybe you gave a few programming tutorials a try but you’re eager for a little more structure. Maybe you even took a CS class once in high school or made a mod for your favorite game. We’ve had very good success teaching absolute beginners. What you know is much less important than what you can learn.</p>

<p>If you’re a little more advanced, you’re welcome too! You may not need to sit through the early material, but if you want a place to work on a personal project, surrounded by smart people who can keep you motivated, you’ll find that here.</p>

<h2>Why Women Only?</h2>
<p>In short, we hate the <a href="http://dev.null.org/blog/item/200305222135_dave2girl" target="_blank">Dave-to-Girl Ratio</a> in software development. We want to do our part to equalize this imbalance, and we felt that a program exclusively for women was a good place to start. For the record, there will only be 1 Dave in the classroom.</p>

<h2>Why Python and Web Development?</h2>
<p>Python is an important part of the tech ecosystem. It’s an excellent teaching language, indeed, it’s the language of choice for both MIT’s and Berkeley’s undergraduate curriculums. More importantly, it’s a commercially used language used by <a href="http://www.google.com" target="_blank">giants</a> and <a href="http://www.instagr.am" target="_blank">startups</a> alike. We like it a lot, and we think you’ll like it too.</p>

<p>Software Development is changing. Within the last ten years, the web has gone from being a second-class citizen to the primary way software is distributed to people. Aside from toys, there is almost no marketplace for software without a network component anymore, and modern web development was critical to that change. Even if you go on to build mobile applications, you’ll need to interface with a web component.</p>

<p>Web development is a bit of a misnomer, too. We teach you how to architect and build multi-user network applications. Then, we show you how to make it pretty in a web browser.</p>

<h2>And after?</h2>
<p>Our goal is to help you get the job you really want. We will provide training on both the technical skills and soft skills you need to make your way into the industry.  While we don't guarantee job placement, we have strategic relationships with companies that we’re excited about and are excited about us and who will be actively recruiting from our program.</p>

<h2>Cost</h2>
<p>Tuition is $6,000 and there are a couple ways of doing the program for free.  We have strategic relationships with companies in the industry. If you receive and accept a full-time job offer from one of the companies in our network then we will refund your tuition in favor of a placement fee. We’re also offering a scholarship to cover the cost of tuition for one student. (If you are an organization who wants to sponsor more students, please <a href="mailto:d@hackstaracademy.com" target="_blank">contact us</a>.) If the program doesn't meet your expectations in the first 2 weeks, we'll give you your money back (less your deposit).</p>



</div>

app/views/shared/_footer.html.erb
<footer class="footer container container-body">
	<hr>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=110202509104041";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	<p>&#169; Hackstar Academy 2012</p>
	</div>	
	<div id="hackstar-share-twitter">
		<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.hackstaracademy.com" data-text="Want to learn how to code? Check out @hackstaracademy's 10-week Programming Fellowship for Women!">Tweet</a>
	</p>	
	</div>
	
	
	<div id="hackstar-share-fb">
	<p>
	<div class="fb-like" data-href="http://www.hackstaracademy.com" data-send="false" data-layout="button_count" data-show-faces="true"></div>
	</p>
	<p>
	
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
		<%#= debug(params) if Rails.env.development? %> 	
</footer>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top" style="margin-top:-35px;">
	
	<div class="navbar-inner">
		
		<div class="container">
			
			<div class="nav-collapse">
				
				<ul class="nav pull-right">
					
					<li class="divider-vertical"></li>
				</ul>
			</div>
			
		</div>
		<ul class="nav nav-pills nav-position">
		  <li class="active">
		    <%= link_to "Home", pages_home_path %>
		  </li>
		  <li class="active">
				<%= link_to "About", pages_about_path %>
			</li>
			<li class="active">
				<%= link_to "Dates", pages_dates_path %>
			</li>
			<li class="active">
				<%= link_to "FAQ", pages_faq_path %>
			</li>
		  <li class="active">
				<%= link_to "Testimonials", pages_testimonials_path %>
			</li>
			<li class="active">
		    <a href="http://hackstaracademy.tumblr.com">Blog</a>
		  </li>
			<!-- <li class="active">
							<a href="http://bit.ly/Ic4s8Y" target="_blank">Apply</a>
						</li>	 -->
		</ul>
	</div>
</div>